# Application Name
spring.application.name=hospital-system

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6sd4qf5gffc738hhtg0-a.oregon-postgres.render.com:5432/hospital_system_ckvt
spring.datasource.username=hospital_system_ckvt_user
spring.datasource.password=gbhrx0994WMZ9nFYlLLM2ZvRo8qxNwuS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT Configuration ✅ (IMPORTANT)
app.jwt.secret=ThisIsASuperLongSecureJWTSecretKeyForHospitalSystem2026AtLeast32Chars
app.jwt.expiration=86400000

# CORS (optional)
spring.mvc.cors.allowed-origins=http://localhost:3000

# Jackson Config
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC

# Logging
logging.level.com.hospital=DEBUG
